spring:
    datasource:
        url: jdbc:mysql://localhost:3306/minor_project1_jbdl88?createDatabaseIfNotExist=true
        username: root
        password: root1234
    jpa:
      hibernate.ddl-auto: update
      show-sql: true

server:
    port: 8080

custom_property:
    property1: values1